Add user, repository, and vault arguments

diff --git a/superlumic b/superlumic
--- a/superlumic
+++ b/superlumic
@@ -3,28 +3,11 @@
 BGreen='\e[1;32m'       # Green
 BRed='\e[1;31m'         # Red
 Color_Off='\e[0m'       # Text Reset
+VERSION="0.1.0"
 
 function setStatusMessage {
     printf "${IRed} --> ${BGreen}$1${Color_Off}\n" 1>&2
 }
-
-printf "${BGreen}   _________                         .__                .__        ${Color_Off}\n"
-printf "${BGreen}  /   _____/__ ________   ___________|  |  __ __  _____ |__| ____  ${Color_Off}\n"
-printf "${BGreen}  \_____  \|  |  \____ \_/ __ \_  __ \  | |  |  \/     \|  |/ ___\ ${Color_Off}\n"
-printf "${BGreen}  /        \  |  /  |_> >  ___/|  | \/  |_|  |  /  Y Y  \  \  \___ ${Color_Off}\n"
-printf "${BGreen} /_______  /____/|   __/ \___  >__|  |____/____/|__|_|  /__|\___  >${Color_Off}\n"
-printf "${BGreen}         \/      |__|        \/ http://superlumic.com \/        \/ ${Color_Off}\n\n"
-
-setStatusMessage "Checking if we need to ask for a sudo password"
-
-sudo -v
-export ANSIBLE_ASK_SUDO_PASS=True
-
-repo=$1
-username=$USER
-if [ ! -z "$2" ]; then
-    username=$2
-fi
 
 function triggerError {
     printf "${BRed} --> $1 ${Color_Off}\n" 1>&2
@@ -43,46 +26,158 @@ function exists {
 
 # credits https://github.com/boxcutter/osx/blob/master/script/xcode-cli-tools.sh
 function install_clt {
-    # Get and install Xcode CLI tools
-    OSX_VERS=$(sw_vers -productVersion | awk -F "." '{print $2}')
+   # Get and install Xcode CLI tools
+   OSX_VERS=$(sw_vers -productVersion | awk -F "." '{print $2}')
 
-    # on 10.9+, we can leverage SUS to get the latest CLI tools
-    if [ "$OSX_VERS" -ge 9 ]; then
-        # create the placeholder file that's checked by CLI updates' .dist code
-        # in Apple's SUS catalog
-        touch /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress
-        # find the CLI Tools update
-        PROD=$(softwareupdate -l | grep "\*.*Command Line" | head -n 1 | awk -F"*" '{print $2}' | sed -e 's/^ *//' | tr -d '\n')
-        # install it
-        softwareupdate -i "$PROD" -v
-        rm /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress
+   # on 10.9+, we can leverage SUS to get the latest CLI tools
+   if [ "$OSX_VERS" -ge 9 ]; then
+       # create the placeholder file that's checked by CLI updates' .dist code
+       # in Apple's SUS catalog
+       touch /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress
+       # find the CLI Tools update
+       PROD=$(softwareupdate -l | grep "\*.*Command Line" | head -n 1 | awk -F"*" '{print $2}' | sed -e 's/^ *//' | tr -d '\n')
+       # install it
+       softwareupdate -i "$PROD" -v
+       rm /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress
 
-    # on 10.7/10.8, we instead download from public download URLs, which can be found in
-    # the dvtdownloadableindex:
-    # https://devimages.apple.com.edgekey.net/downloads/xcode/simulators/index-3905972D-B609-49CE-8D06-51ADC78E07BC.dvtdownloadableindex
-    else
-        [ "$OSX_VERS" -eq 7 ] && DMGURL=http://devimages.apple.com.edgekey.net/downloads/xcode/command_line_tools_for_xcode_os_x_lion_april_2013.dmg
-        [ "$OSX_VERS" -eq 7 ] && ALLOW_UNTRUSTED=-allowUntrusted
-        [ "$OSX_VERS" -eq 8 ] && DMGURL=http://devimages.apple.com.edgekey.net/downloads/xcode/command_line_tools_for_osx_mountain_lion_april_2014.dmg
+   # on 10.7/10.8, we instead download from public download URLs, which can be found in
+   # the dvtdownloadableindex:
+   # https://devimages.apple.com.edgekey.net/downloads/xcode/simulators/index-3905972D-B609-49CE-8D06-51ADC78E07BC.dvtdownloadableindex
+   else
+       [ "$OSX_VERS" -eq 7 ] && DMGURL=http://devimages.apple.com.edgekey.net/downloads/xcode/command_line_tools_for_xcode_os_x_lion_april_2013.dmg
+       [ "$OSX_VERS" -eq 7 ] && ALLOW_UNTRUSTED=-allowUntrusted
+       [ "$OSX_VERS" -eq 8 ] && DMGURL=http://devimages.apple.com.edgekey.net/downloads/xcode/command_line_tools_for_osx_mountain_lion_april_2014.dmg
 
-        TOOLS=clitools.dmg
-        curl "$DMGURL" -o "$TOOLS"
-        TMPMOUNT=`/usr/bin/mktemp -d /tmp/clitools.XXXX`
-        hdiutil attach "$TOOLS" -mountpoint "$TMPMOUNT"
-        installer $ALLOW_UNTRUSTED -pkg "$(find $TMPMOUNT -name '*.mpkg')" -target /
-        hdiutil detach "$TMPMOUNT"
-        rm -rf "$TMPMOUNT"
-        rm "$TOOLS"
-        exit
-    fi
+       TOOLS=clitools.dmg
+       curl "$DMGURL" -o "$TOOLS"
+       TMPMOUNT=`/usr/bin/mktemp -d /tmp/clitools.XXXX`
+       hdiutil attach "$TOOLS" -mountpoint "$TMPMOUNT"
+       installer $ALLOW_UNTRUSTED -pkg "$(find $TMPMOUNT -name '*.mpkg')" -target /
+       hdiutil detach "$TMPMOUNT"
+       rm -rf "$TMPMOUNT"
+       rm "$TOOLS"
+       exit
+   fi
 }
 
+#
+# Print version information
+#
+# $1: the version
+#
+function show_version
+{
+    echo "${0##*/} $VERSION"
+    exit 0
+}
+
+#
+# Echos text to strerr.
+#
+# $1: the text to echo
+#
+function error
+{
+    echo "error: $1" >&2
+    exit 1
+}
+
+function print_usage
+{
+    echo "usage: superlumic [-h] [-v] [-a | -f FILE] [-u USER]"
+}
+
+function show_help
+{
+    print_usage
+    echo
+    echo "Superlumic is a light utility wrapper around Ansible to ease the automated install"
+    echo "of OSX 10.10 and higher."
+    echo
+    echo "optional arguments"
+    echo "  -h, --help            show this help message and exit"
+    echo "  -v, --version         show program's version number and exit"
+    echo "  -u, --user USER       name of user playbook (default: current user)"
+    echo "  -a, --ask-vault-pass  ask for vault password"
+    echo "  -f, --vault-password-file"
+    echo "                        vault password file or script"
+    echo
+    echo "for more detail, use: man superlumic"
+    exit 0
+}
+
+# parse comment line arguments
+username="$(whoami)"
+repo=https://github.com/Brickstertwo/superlumic-config
+ask_vault_pass=false
+vault_password_file=
+while getopts ":hvu:r:af:-:" opt; do
+    case $opt in
+        -)
+            case "${OPTARG}" in
+                user)
+                    username="${!OPTIND}"
+                    OPTIND=$(( $OPTIND + 1 ))
+                    if [[ -z "$username" ]]; then
+                        error "Option --$OPTARG requires an argument."
+                    fi
+                    ;;
+                repository)
+                    repo="${!OPTIND}"
+                    OPTIND=$(( $OPTIND + 1 ))
+                    if [[ -z "$repo" ]]; then
+                        error "Option --$OPTARG requires an argument."
+                    fi
+                    ;;
+                ask-vault-pass)
+                    ask_vault_pass=true
+                    ;;
+                vault-password-file)
+                    vault_password_file="${!OPTIND}"
+                    OPTIND=$(( $OPTIND + 1 ))
+                    if [[ -z "$vault_password_file" ]]; then
+                        error "Option --$OPTARG requires an argument."
+                    fi
+                    ;;
+                help)                   show_help;;
+                version)                show_version;;
+                *)                      error "Unimplemented option --${OPTARG}";;
+            esac
+            ;;
+        u)  username="$OPTARG";;
+        r)  repo="$OPTARG";;
+        a)  ask_vault_pass=true;;
+        f)  vault_password_file="$OPTARG";;
+        h)  show_help;;
+        v)  show_version;;
+        \?) error "Invalid option: -$OPTARG";;
+        :)  error "Option -$OPTARG requires an argument.";;
+        *)  error "Unimplemented option: -$OPTARG";;
+    esac
+done
+
+if $ask_vault_pass && [[ ! -z "$vault_password_file" ]]; then
+    print_usage
+    error "options -a|--ask-vault-pass and -f|--vault-password-file FILE are mutually exclusive"
+fi
+
+export HOMEBREW_CASK_OPTS="--appdir=/Applications"
+
+printf "${BGreen}   _________                         .__                .__        ${Color_Off}\n"
+printf "${BGreen}  /   _____/__ ________   ___________|  |  __ __  _____ |__| ____  ${Color_Off}\n"
+printf "${BGreen}  \_____  \|  |  \____ \_/ __ \_  __ \  | |  |  \/     \|  |/ ___\ ${Color_Off}\n"
+printf "${BGreen}  /        \  |  /  |_> >  ___/|  | \/  |_|  |  /  Y Y  \  \  \___ ${Color_Off}\n"
+printf "${BGreen} /_______  /____/|   __/ \___  >__|  |____/____/|__|_|  /__|\___  >${Color_Off}\n"
+printf "${BGreen}         \/      |__|        \/ http://superlumic.com \/        \/ ${Color_Off}\n\n"
+
+setStatusMessage "Checking if we need to ask for a sudo password"
+sudo -v
+export ANSIBLE_ASK_SUDO_PASS=True
 setStatusMessage "Keep-alive: update existing sudo time stamp until we are finished"
 
 while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &
 
-export HOMEBREW_CASK_OPTS="--appdir=/Applications"
-
+# install CLT
 if [[ ! -f "/Library/Developer/CommandLineTools/usr/bin/clang" ]]; then
     setStatusMessage "Install the CLT"
     install_clt
@@ -100,7 +195,6 @@ if ! exists ansible; then
 fi
 
 setStatusMessage "Create necessary folders"
-
 sudo mkdir -p /usr/local/superlumic
 sudo mkdir -p /usr/local/superlumic/roles
 sudo chmod -R g+rwx /usr/local
@@ -132,7 +226,13 @@ ansible-galaxy install -f -r config/requirements.yml -p roles
 
 if [ -f "config/$username.yml" ]; then
     setStatusMessage "Running the ansible playbook for $username"
-    ansible-playbook -i "localhost," config/$username.yml
+    if $ask_vault_pass; then
+        ansible-playbook -i "localhost," config/$username.yml --ask-vault-pass
+    elif [[ ! -z "$vault_password_file" ]]; then
+        ansible-playbook -i "localhost," config/$username.yml --vault-password-file "$vault_password_file"
+    else
+        ansible-playbook -i "localhost," config/$username.yml
+    fi
 else
     if [ "travis" = "$username" ]; then
         setStatusMessage "Running the ansible playbook for $username but use roderik.yml as fallback"
